import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider";
import { Toaster } from "@/components/ui/toaster";
import { Apollo } from "@/libs/Apollo";
import { Box } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Movies Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Apollo>
          <Provider>
              {children}
            <Toaster />
          </Provider>
        </Apollo>
      </body>
    </html>
  );
}
