import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider";
import { Apollo } from "../libs/Apollo";

export const metadata: Metadata = {
  title: "Movies Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Apollo>
          <Provider>
            {children}
          </Provider>
        </Apollo>
      </body>
    </html>
  );
}
